# frozen_string_literal: true

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-param'

gem 'faraday'

gem 'sanitize'

gem 'classifier-reborn', github: "jekyll/classifier-reborn"
gem 'natto'
